/**
 * Created by nkhristinin on 08.10.16.
 */
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const REDUCE_PRODUCT_COUNT = 'REDUCE_PRODUCT_COUNT';
export const BUY_PRODUCT_REQUEST = 'BUY_PRODUCT_REQUEST';
export const BUY_PRODUCT_SUCCESS = 'BUY_PRODUCT_SUCCESS';
export const BUY_PRODUCT_FAILURE = 'BUY_PRODUCT_FAILURE';
